- name: ====== LINUX CLIENT MONITORING ======
  hosts: all
  gather_facts: yes
  vars:
    - file_check: "output/tmp/check-{{ ansible_hostname }}.txt"
  tasks:
    - name: Report Directory
      file:
        path: output/tmp
        state: directory
        mode: 0777
    - shell: rm -rf ouput/tmp/*.txt

    - name: CPU Usage
      shell: top -bn1 | grep 'Cpu(s)' | awk '{print $2}'
      register: cpu_usage
#    - name: RAM Usage
#      shell: top -bn1 | awk '/MiB mem/ {printf "%.2f\n", $8/$4 * 100}'
#      register: ram_usage
    - name: Gather Disk Space
      shell: "df -h --output=pcent / | awk 'NR==2 {print $1}'"
      register: disk_space
    - name: Date
      debug:
        msg:
             - "=========================="
             - "Waktu Mulai Monitoring: {{ ansible_date_time.date }} {{ ansible_date_time.hour }}:{{ ansible_date_time.minute }}"
             - "=========================="
             - "CPU USAGE : {{ cpu_usage.stdout }} %"
             - "RAM USAGE : {{ ansible_memory_mb.real.used }} GB"
             - "DISK SPACE USAGE : {{ disk_space.stdout }} %"
             - "System {{ inventory_hostname }} has gateway {{ ansible_default_ipv4.gateway }}"

    - name: Usage Stats
      copy:
        content: |
             - "=========================="
             - "Waktu Mulai Monitoring: {{ ansible_date_time.date }} {{ ansible_date_time.hour }}:{{ ansible_date_time.minute }}"
             - "=========================="
             - "CPU USAGE : {{ cpu_usage.stdout }} %"
             - "RAM USAGE : {{ ansible_memory_mb.real.used }} GB"
             - "DISK SPACE USAGE : {{ disk_space.stdout }} %"
             - "System {{ inventory_hostname }} has gateway {{ ansible_default_ipv4.gateway }}"
        dest: "{{ file_check }}"
      register: output_file
    - name: Collecting Report
      fetch:
        src: "{{ item }}"
        dest: output/tmp/
      with_items:
        - "{{ file_check }}"
