- name: ====== INSTALL/UNINSTALL '{{serv}}' ======
  hosts: PGD-SBY
  gather_facts: yes
  become: yes
  vars_prompt:

    - name: serv
      prompt: Service
      private: false
    - name: ins
      prompt: latest/absent
      private: false
    - name: state_serv
      prompt: started/stopped
      private: false
    - name: condition
      prompt: yes/false
      private: false
  tasks:
    - name: Install/Uninstall '{{serv}}'
      apt:
        name: '{{serv}}'
        state: '{{ins}}'
    - name: Service for '{{state_serv}}' '{{serv}}'
      service:
        name: '{{serv}}'
        state: '{{state_serv}}'
        enabled: '{{condition}}'
    - name: Check Status Service
      shell: systemctl status '{{serv}}' | grep 'Active' | tr -d '\t '
      register: log
    - name: Debug
      debug:
        msg:
          - " Service Check Target       : {{ ansible_hostname }} : {{ inventory_hostname }}  "
          - " Time                       : {{ ansible_date_time.date }} {{ ansible_date_time.hour}}:{{ansible_date_time.minute}}"
          - " Debug                      : {{ log.stdout }} "

