- name: ====== CONFIGURE SNMP ======
  hosts: client-1
  gather_facts: yes
  become: yes
#  vars_prompt:

#    - name: serv
#      prompt: Service
#      private: false
#    - name: state_serv
#      prompt: started/stopped
#      private: false
#    - name: condition
#      prompt: yes/false
#      private: false
  tasks:
    - name: Update Configuration
      lineinfile:
        path: /etc/snmp/snmpd.conf
        regexp: 'rocommunity P3g4d414n_RO'
        state: absent
#    - name: Add Line to Config
#      lineinfile:
#        path: /etc/snmp/snmpd.conf
#        line: 'rocommunity P3g4d414n_RO'
#        insertafter: '#   arguments viewname included [oid]'
#    - name: Restart SNMP after Update
#      service:
#        name: snmpd
#        state: restarted
#    - name: Debug
#      debug:
#        msg:
#          - " Service Check Target       : {{ ansible_hostname }} : {{ inventory_hostname }}  "
#          - " Time                       : {{ ansible_date_time.date }} {{ ansible_date_time.hour}}:{{ansible_date_time.minute}}"
#          - " Debug                      : {{ log.stdout }} "

